[workspace]
resolver = "2"
members = [
    "crates/emp-app",
    "crates/emp-core",
    "crates/emp-protocol",
    "crates/emp-state",
]

[workspace.package]
version = "0.11.6"
edition = "2024"
license = "MIT"

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.release]
lto = true
codegen-units = 1
strip = true
