import {test} from 'node:test';
import assert from 'node:assert/strict';
import {boot,settle} from './harness.mjs';
import {integrationFixture} from './fixtures.mjs';

test('page boots and preserves all existing surfaces without automatic verification',async()=>{
 const f=await boot();try{assert.deepEqual(f.errors,[]);assert.equal(f.d.querySelectorAll('.source-node').length,4);assert.match(f.d.querySelector('#connection_headline').textContent,/目录已匹配/);assert.equal(f.d.querySelector('#models_workspace').hidden,true);f.w.setWorkspace('models');assert.equal(f.d.querySelector('#models_workspace').hidden,false);for(const id of ['accounts','providers','models','catalog_display_models'])assert.ok(f.d.getElementById(id));assert.equal(f.mock.calls.some(c=>c.path.includes('/verify')||c.path.startsWith('/v1/')||c.path.includes('/quota')),false);}finally{f.close();}
});
test('stale or mismatched catalog evidence never turns green',async()=>{
 const f=await boot();try{for(const s of ['pending','failed','stale','native','conflict'])assert.notEqual(f.w.connectionEvidence(integrationFixture(s)).tone,'confirmed');const loaded=integrationFixture();for(const mutation of [{catalog_verified:false},{confidence:'stale'},{target:'native'},{target_matches_saved_configuration:false}])assert.notEqual(f.w.connectionEvidence({...loaded,runtime:{...loaded.runtime,...mutation}}).tone,'confirmed');assert.equal(f.w.connectionEvidence({...loaded,configuration:{state:'emp_applied',stale:true}}).tone,'unknown');f.w.openConnectionDetails();assert.match(f.d.querySelector('#modal_body').textContent,/模型请求与原生恢复：未验证/);}finally{f.close();}
});
test('source and Codex details are passive, show routes and observation times',async()=>{
 const f=await boot();try{const before=JSON.stringify(f.mock.config),count=f.mock.calls.length;f.d.querySelector('[data-source-key="account:work"]').click();assert.match(f.d.querySelector('#modal_body').textContent,/work\/gpt-example/);assert.match(f.d.querySelector('#modal_body').textContent,/观测于/);f.w.closeModal();f.w.openSourceDetails('account','personal');assert.match(f.d.querySelector('#modal_body').textContent,/暂无额度观测时间/);f.w.closeModal();f.w.openSourceDetails('provider','research');assert.match(f.d.querySelector('#modal_body').textContent,/research\/claude-example/);f.w.closeModal();f.w.openConnectionDetails();assert.equal(f.mock.calls.length,count);assert.equal(JSON.stringify(f.mock.config),before);}finally{f.close();}
});
test('catalog retry keeps successful import and never enables EMP',async()=>{
 const f=await boot('native');try{f.w.openAddSource();f.w.openAccountImportHelp();await f.w.accountFileChosen({files:[{name:'test.backup',text:async()=>'{"test_fixture":true}'}]});f.d.querySelector('#modal_account_name').value='研究 <账号>';const id=f.d.querySelector('#modal_account_id').value;assert.equal(id,'account-1');f.mock.setCatalogFailure(true);await f.w.submitAccountImport();assert.match(f.d.querySelector('#modal_title').textContent,/账号已保存，目录同步未完成/);assert.equal(f.mock.config.accounts.at(-1).name,'研究 <账号>');f.mock.setCatalogFailure(false);await f.w.finishAccountImport();assert.equal(f.mock.calls.filter(c=>c.path==='/api/accounts/import').length,1);assert.equal(f.mock.calls.some(c=>c.path==='/api/integration/enable'),false);assert.equal(f.mock.config.accounts.at(-1).prefix,id);}finally{f.close();}
});
test('duplicate IDs rejected; explicit reimport preserves stable identity and visibility',async()=>{
 const f=await boot();try{f.w.openAccountImportHelp();await f.w.accountFileChosen({files:[{name:'test.json',text:async()=>'{"test_fixture":true}'}]});f.d.querySelector('#modal_account_name').value='duplicate';f.d.querySelector('#modal_account_id').value='work';await assert.rejects(f.w.submitAccountImport(),/已被使用/);f.w.openAccountImportHelp('work');await f.w.accountFileChosen({files:[{name:'test.json',text:async()=>'{"test_fixture":true}'}]});assert.equal(f.d.querySelector('#modal_account_id').readOnly,true);await f.w.submitAccountImport();const sent=f.mock.calls.find(c=>c.path==='/api/accounts/import').body;assert.equal(sent.id,'work');assert.equal(sent.prefix,'work');assert.deepEqual(sent.hidden_models,[]);}finally{f.close();}
});
test('missing quota is unknown and identity text is escaped',async()=>{
 const f=await boot();try{assert.equal(f.w.quotaBuckets({quota:{rate_limits:{primary:{usedPercent:null}}}}).length,0);assert.doesNotMatch(f.w.quotaMetersHtml({quota:{rate_limits:{primary:{usedPercent:10,windowDurationMins:300}}}}),/233%/);f.w.eval(`state.accounts[0].name='<img src=x onerror=alert(1)>';renderConnections()`);assert.equal(f.d.querySelectorAll('.source-node img').length,0);assert.match(f.d.querySelector('.source-node[data-id="work"]').textContent,/<img/);}finally{f.close();}
});
test('source list collapses, searches, and retains actions in list mode',async()=>{
 const f=await boot('many');try{assert.equal(f.d.querySelectorAll('.source-node').length,6);f.d.querySelector('#source_expand').click();assert.equal(f.d.querySelectorAll('.source-node').length,15);f.d.querySelector('#source_search').value='研究账号 13';f.w.renderConnections();assert.equal(f.d.querySelectorAll('.source-node').length,1);f.w.setConnectionView('list');assert.equal(f.d.querySelector('#connection_canvas').dataset.view,'list');}finally{f.close();}
});
test('modal isolates background and restores focus; bilingual navigation',async()=>{
 const f=await boot();try{const trigger=f.d.querySelector('[data-source-key="account:work"]');trigger.focus();trigger.click();await settle();assert.equal(f.d.querySelector('main').inert,true);assert.equal(f.d.activeElement.className,'modal-close');f.d.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(f.d.querySelector('main').inert,false);assert.equal(f.d.activeElement,trigger);f.w.setLanguage('en');assert.match(f.d.querySelector('[data-i18n="connections_title"]').textContent,/Your accounts/);}finally{f.close();}
});
test('quit accepted and disconnect never imply restored Codex or safe exit',async()=>{
 const f=await boot();try{f.w.confirm=()=>false;await f.w.quitEmp();assert.equal(f.mock.calls.some(c=>c.path==='/api/quit'),false);f.w.confirm=()=>true;await f.w.quitEmp();assert.match(f.d.querySelector('#modal_title').textContent,/退出请求已接受/);assert.match(f.d.querySelector('#lifecycle_status').textContent,/正在停止/);f.w.setConnectionTransport('disconnected');assert.match(f.d.querySelector('#lifecycle_status').textContent,/尚未确认/);assert.equal(f.d.querySelector('#integration_toggle').disabled,true);assert.doesNotMatch(f.d.querySelector('#modal_body').textContent,/EMP 已退出|已恢复原生配置，可以/);}finally{f.close();}
});
test('initial connection failure is readable without hidden mutations',async()=>{
 const f=await boot('offline');try{assert.match(f.d.querySelector('#connection_headline').textContent,/断开/);assert.match(f.d.querySelector('#status').textContent,/Failed to fetch/);assert.equal(f.d.querySelector('#connection_next_action').disabled,false);f.w.setConnectionTransport('connected');assert.match(f.d.querySelector('#connection_headline').textContent,/配置读取未完成/);assert.equal(f.mock.calls.some(c=>c.method==='POST'&&!['/api/session','/api/client-events'].includes(c.path)),false);}finally{f.close();}
});

test('legacy dialogs open with real page bindings and preserve independent update warning',async()=>{
 const f=await boot();try{f.w.openUsage();await settle();assert.ok(f.d.querySelector('#usage_result'));assert.doesNotMatch(f.d.querySelector('#usage_status').textContent,/undefined|not iterable/);f.w.closeModal();f.w.eval('openDiagnostics()');await settle();assert.match(f.d.querySelector('#diagnostics_summary').textContent,/完成几次模型调用/);f.w.closeModal();f.w.eval('openSettings()');assert.equal(f.d.querySelectorAll('.setting-switch').length,3);f.w.closeModal();await f.w.openUpdate();assert.match(f.d.querySelector('#modal_body').textContent,/不是本分支更新/);f.w.closeModal();assert.match(f.w.activityDescription('work',{inFlight:0,lastFinished:null,recent:false}),/尚未观测/);assert.deepEqual(f.errors,[]);}finally{f.close();}
});
